/**
 * Run: npx tsx src/utils/storyImages.test.ts
 *
 * Where a passage's pictures come from.
 *
 * A story carries images three ways — attached to the message, written inline
 * in the prose, and generated by the reader for a beat — and every view that
 * wanted them was finding one or two of the three. The Panels view shipped
 * reading only the generated ones, which made a comic view that looked broken
 * for anyone who had not run an image model; Stage and VN each had their own
 * copy of the attached+inline walk and neither knew about generated art.
 *
 * So the property this file guards is simply: **all three, in a stable order,
 * with nothing counted twice.**
 *
 * The second property is the one Stage and VN already relied on and nobody had
 * written down: a scene picture HOLDS until a newer one replaces it. A backdrop
 * that blinks out on the one passage that happens to have no image reads as a
 * bug, not as an absence.
 */
import { hasImage, imagesAcross, imagesOf, latestImages } from './storyImages';

let pass = 0, fail = 0;
const ok = (cond: boolean, msg: string) => { if (cond) { pass++; } else { fail++; console.error('✗', msg); } };
const eq = (a: unknown, b: unknown, msg: string) => {
  if (JSON.stringify(a) === JSON.stringify(b)) pass++;
  else { fail++; console.error('✗', msg, `\n    got ${JSON.stringify(a)}\n    want ${JSON.stringify(b)}`); }
};

const m = (content: string, images?: string[]) => ({ content, images });

/* ── All three sources ───────────────────────────────────────────────────── */
{
  eq(imagesOf(m('plain prose')), [], 'a passage with nothing has nothing');
  eq(imagesOf(m('x', ['a.png'])), ['a.png'], 'attached');
  eq(imagesOf(m('see ![alt](b.png) here')), ['b.png'], 'inline markdown');
  eq(imagesOf(m('x'), ['blob:c']), ['blob:c'], 'generated for the beat');

  eq(imagesOf(m('and ![](b.png)', ['a.png']), ['blob:c']), ['a.png', 'b.png', 'blob:c'],
    'attached, then inline, then generated — the order they were added in');

  eq(imagesOf(m('![](x.png) and ![](y.png)')), ['x.png', 'y.png'],
    'more than one inline, in reading order');
  eq(imagesOf(m('![a](p.png)\n\n![b](p.png)')), ['p.png'],
    'the same picture twice is one picture');
  eq(imagesOf(m('x', ['a.png']), ['a.png']), ['a.png'],
    'and that holds across sources — a re-roll can land on a URL already attached');

  // A markdown link is not an image.
  eq(imagesOf(m('a [link](page.html) here')), [], 'a link is not a picture');
  // Nor is a bare URL.
  eq(imagesOf(m('http://example.com/x.png')), [], 'nor a bare URL in the prose');
  // Nothing empty ever reaches a src attribute.
  eq(imagesOf(m('x', ['', 'a.png'])), ['a.png'], 'an empty entry is dropped, not rendered');
}

/* ── The cheap check ─────────────────────────────────────────────────────── */
{
  ok(!hasImage(m('nothing here')), 'no pictures');
  ok(hasImage(m('x', ['a.png'])), 'attached');
  ok(hasImage(m('![](b.png)')), 'inline');
  ok(hasImage(m('x'), ['blob:c']), 'generated');
  // A global regex carries lastIndex between calls; calling twice must not
  // start returning false on the second look.
  const one = m('![](b.png)');
  ok(hasImage(one) && hasImage(one), 'asked twice, answers the same twice');
}

/* ── A scene picture holds ───────────────────────────────────────────────── */
{
  const timeline = [
    m('opening', ['first.png']),
    m('a passage with no picture at all'),
    m('another one'),
  ];
  eq(latestImages(timeline), ['first.png'],
    'the last passage that HAS one wins — the world does not blink out between lines');

  eq(latestImages([...timeline, m('later', ['second.png'])]), ['second.png'],
    'and a newer one replaces it');

  eq(latestImages([m('nothing'), m('still nothing')]), [], 'nothing at all is nothing');
  eq(latestImages([]), [], 'an empty timeline');

  // Generated art counts as a picture for this too.
  eq(latestImages([m('a'), m('b')], (x) => (x.content === 'b' ? ['blob:z'] : undefined)),
    ['blob:z'], 'generated art holds the scene like any other picture');
}

/* ── Everything across a run ─────────────────────────────────────────────── */
{
  const run = [m('a', ['1.png']), m('![](2.png)'), m('c'), m('d', ['1.png'])];
  eq(imagesAcross(run), ['1.png', '2.png'],
    'every picture in the run, in reading order, each once');
  eq(imagesAcross([]), [], 'an empty run');
  eq(imagesAcross(run, (x) => (x.content === 'c' ? ['blob:g'] : undefined)),
    ['1.png', '2.png', 'blob:g'], 'generated art takes its place in the order');
}

console.log(`${pass} passed, ${fail} failed`);
if (fail) process.exit(1);
