/**
 * Cut the shipped logo down to the two marks the app actually uses.
 *
 * Run: node scripts/build-logo.mjs   (source: aeialogo.png, 1024², transparent)
 *
 * The emblem — book, halo, hands — is the only part that travels. The wordmark
 * is not baked in anywhere: the app writes "Aeia Reader" as live text so it
 * takes the reader's theme and font, and stays legible at any size.
 *
 * Three outputs:
 *   public/favicon.png     the browser/desktop tab icon
 *   src/assets/aeiaMark.ts the same emblem as a data URI, because it is stamped
 *                          into EXPORTED files, which may not fetch anything.
 *                          A bundled data URI is the only self-contained way in.
 *   src-tauri/icons/app-source.png  a 1024² square master for `tauri icon`,
 *                          which builds the desktop app's own icon set from it
 *                          (.ico included — encoding one of those by hand here
 *                          would be a worse version of a tool we already have).
 *                          Run `npx tauri icon src-tauri/icons/app-source.png`
 *                          after this script when the logo changes.
 *
 * Regenerate only when the logo changes; all outputs are committed.
 */
import { chromium } from '@playwright/test';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';

const staged = path.join(os.homedir(), '.cache/pw-syslibs/root/usr/lib/x86_64-linux-gnu');
if (fs.existsSync(staged)) {
  process.env.LD_LIBRARY_PATH = [staged, process.env.LD_LIBRARY_PATH].filter(Boolean).join(':');
}

const SRC = 'aeialogo.png';
/**
 * The book-and-halo, measured off the source as the bounding box of everything
 * SATURATED (the hands either side are a pale grey wireframe). Cropping to the
 * whole emblem including the hands was the obvious move and the wrong one: the
 * hands are thin, low-contrast and nearly white, so they disappeared on a light
 * theme and turned to noise at the 18px this mark is drawn at in an export
 * corner. The book alone is high-contrast, near-square, and survives 16px.
 */
const CROP = { x: 298, y: 253, w: 430, h: 407 };

const browser = await chromium.launch({ args: ['--no-sandbox'] });
const page = await browser.newPage();
const src = `data:image/png;base64,${fs.readFileSync(SRC).toString('base64')}`;

/** Draw the crop into a `width`-wide canvas, padded square when asked. */
const cut = (width, square, type = 'image/png') => page.evaluate(async ({ src, crop, width, square, type }) => {
  const img = new Image();
  img.src = src;
  await img.decode();
  const scale = width / crop.w;
  const h = Math.round(crop.h * scale);
  const c = document.createElement('canvas');
  c.width = width;
  c.height = square ? width : h;
  const g = c.getContext('2d');
  g.imageSmoothingQuality = 'high';
  g.drawImage(img, crop.x, crop.y, crop.w, crop.h, 0, square ? (width - h) / 2 : 0, width, h);
  return c.toDataURL(type, 0.92);
}, { src, crop: CROP, width, square, type });

const write = (file, dataUrl) => {
  const bytes = Buffer.from(dataUrl.split(',')[1], 'base64');
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, bytes);
  return bytes.length;
};

const favicon = await cut(128, true);
console.log(`public/favicon.png       ${write('public/favicon.png', favicon)} bytes`);

// Wide enough to stay crisp on a 2x screen at the ~40px it is drawn at, small
// enough that stamping it into every export costs nothing worth noticing.
// WebP with alpha: 9.7KB of data URI against 33KB for the same PNG, and this
// string is carried by every exported .html and .md.
const mark = await cut(160, false, 'image/webp');
fs.mkdirSync('src/assets', { recursive: true });
fs.writeFileSync('src/assets/aeiaMark.ts',
  `/**
 * The Aeia emblem as a data URI — generated by \`scripts/build-logo.mjs\`.
 *
 * A data URI rather than a file in \`public/\` because this mark is stamped into
 * EXPORTED documents, and an exported file is never allowed to fetch anything.
 * The wordmark is deliberately not part of it: "Aeia Reader" is written as live
 * text wherever this appears, so it takes the surrounding theme and font.
 */
export const AEIA_MARK = '${mark}';

/** Natural aspect of the emblem, so callers can size it by height alone. */
export const AEIA_MARK_RATIO = ${(CROP.w / CROP.h).toFixed(4)};
`);
console.log(`src/assets/aeiaMark.ts   ${mark.length} chars of data URI`);

// The master the desktop icon set is cut from. Square and full-size: `tauri
// icon` downsamples to every platform size itself, and giving it the cropped
// 128px favicon instead would ship a blurry taskbar icon on any HiDPI screen.
const appIcon = await cut(1024, true);
console.log(`src-tauri/icons/app-source.png  ${write('src-tauri/icons/app-source.png', appIcon)} bytes`);
console.log('  → now run: npx tauri icon src-tauri/icons/app-source.png');

await browser.close();
